import sample_data
from models import Participant, Session
from analyzer import FitnessAnalyzer
from sample_data import get_sample_scenarios
from utils import format_console_report

def main():
    scenarios = get_sample_scenarios()  # retrieves from sample_data.py
    analyzer = FitnessAnalyzer.create_default()

    for name, (profile_dict, raw_logs) in scenarios.items():
        participant = Participant.from_profile(profile_dict, age=30)
        session = Session(f"SESS-{name.upper()}", participant)

        # ingests observations generated by data_generator.py
        for log in raw_logs:
            session.add_observation(log)

        # Produces a structured dict output and displays it
        result_dict = analyzer.analyze(session)
        print(f"\n--- Scenario: {name.upper()} ---")
        print(format_console_report(result_dict))


if __name__ == '__main__':
    main()
